### ISSUE TITLE
Could not connect to node at http://127.0.0.1:8545 (Error: spawn UNKNOWN).

### ISSUE THREAD

**Issue by aquiladev** [OpenZeppelin/openzeppelin-gsn-helpers#13]
When I run ganache-cli and then try to run relayer, I have an issue
`Could not connect to node at http://127.0.0.1:8545 (Error: spawn UNKNOWN).`

I've checked ganache-cli, it runs on exactly 'http://127.0.0.1:8545' url

**Comment by nventuro** [comment]
@aquiladev did you solve this issue on your own? If so, would you mind posting what the solution was? Thanks!

**Comment by aquiladev** [comment]
I use Windows.
We figured out that it doesn't work properly on Windows.
The issue was in command `oz-gsn run-relayer`, it simply does not download right release, because there is extension `.exe` for Windows.
In order to do a quick fix, guys uploaded the version without extension. You can see it https://github.com/OpenZeppelin/openzeppelin-gsn-helpers/releases/tag/v0.1.4

After the fix, I cleaned the cache (`C:\Users\{USER}\AppData\Local\gsn-nodejs\Cache`) and ran the command again. FIXED
