### ISSUE TITLE
Failed download of relayer is not retried

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-gsn-helpers#15]
The run-relayer command tries to download the relayer binary, but if the download fails, it leaves a corrupt (or even empty) file in the local cache, and never attempts to re-download it.

We should check that the downloaded file is fine, and re-download the binary.

**Comment by nventuro** [comment]
Fixed in 116095bb5ba2e1ec6af74fa68dbcb9c5fa1e7a8c. I couldn't get any two sha3 calculators to output the same value for a given file, so I ended up using `web3-utils.sha3` to calculate the checksums for each binary.
