### ISSUE TITLE
Question about 'src/deploy.js' logging to console.error 

### ISSUE THREAD

**Issue by cgewecke** [OpenZeppelin/openzeppelin-gsn-helpers#21]
I am launching oz-gsn using `child_process.exec` and listening to its stdout/stderr streams. Output that seems legitimate is [being routed to console.error](https://github.com/OpenZeppelin/openzeppelin-gsn-helpers/blob/de67c15637a9361554a5d570a60afc73c5171788/src/deploy.js#L5-L29). Is this intended?

**Comment by nventuro** [comment]
Yes - the idea in our logs is that `stdout` can be consumed by other tools, and all user-facing logging happens on `stderr`. For example, a command deploying a contract may only output on `stdout` the contract's address.

**Comment by cgewecke** [comment]
@nventuro Ah! Understood, thank you.
