### ISSUE TITLE
Deploying to private network

### ISSUE THREAD

**Issue by crossoveranx** [OpenZeppelin/openzeppelin-gsn-helpers#24]
I attempted to deploy the GSN contracts to a private network that is similar to Kovan. I currently have deployed the RelayHub Contracts, however when I call:

`npx oz-gsn register-relayer --ethereumNodeURL http://localhost:8550`

where the ethereumNodeURL is a node with a funded and unlocked account, I receive the following error:

```
Funding GSN relay at http://localhost:8090
(node:2046) UnhandledPromiseRejectionWarning: Error: Failed to fund relay: 'Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0xb22a0a909b55dd9c37705f8a7fad2fab2b3acb09b59a416739339a9bf40efcfa",
  "blockNumber": 3892945,
  "contractAddress": null,
  "cumulativeGasUsed": 1600000,
  "from": "0xab59a1ea1ac9af9f77518b9b4ad80942ade35088",
  "gasUsed": 1600000,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "root": null,
  "status": false,
  "to": "0xd216153c06e857cd7f72665e0af1d7d82172f494",
  "transactionHash": "0xf690d5ecfbed8b403637a0ec46df38969ac87521c9b22ef7b29c97f599f281c9",
  "transactionIndex": 0,
  "events": {}
}'
    at registerRelay (/home/james/Bloxberg/gsn-dapp/node_modules/@openzeppelin/gsn-helpers/src/register.js:48:11)
(node:2046) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:2046) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I can verify that the RelayHub contract is deployed at the usual address 0xd216153c06e857cd7f72665e0af1d7d82172f494. Please let me know if this is possible with this library to deploy or stake a private network GSN RelayHub

Thanks

**Comment by abcoathup** [comment]
Hi @crossoveranx,

There are some instructions on how you should be able to set up GSN on a public network in the OpenZeppelin Community Forum: https://forum.openzeppelin.com/t/running-relayer-on-custom-network/1663/8

Feel free to ask questions in the forum.  
Also to share your setup steps, as you are the third community member who has been looking to set up on a different network.

**Comment by nventuro** [comment]
This might be either the staking or the funding of the relayer that fails: sadly, with the current code it is not possible to deduce from the logs alone. Could you check if the `stake` function was called on RelayHub (and a `Staked` event emitted)? Also, can you verify that account `0xab59a1ea1ac9af9f77518b9b4ad80942ade35088` on your node has enough balance? Keep in mind staking requires a minimum deposit of 1 Eth.

**Comment by crossoveranx** [comment]
I can confirm the node has enough balance.

It seems that any of the functions result in a thrown error. I have also tried calling functions while importing the deployed contract from an IDE like remix and it throws an error as well. For instance, when interacting with IRelayHub and calling the getRelay Function, it throws an error of: 

`"message" must be a nonempty string. `

As background I used the tabookey-gasless repository to conduct the initial deployment, specifically these scripts: 

```
Run: scripts/singleton/compute.sh to generate deployment artifacts
And then scripts/singleton/deploy.js to deploy it.
```

Again, when utilizing your instructions in your link @abcoathup, I get to the point where I have to register relayer which throws the previously mentioned errors. I would be happy to help troubleshoot and document my steps if successful for future use if you have any ideas of what to try.

**Comment by nventuro** [comment]
Those scripts should be equivalent to running `deploy-relay-hub` - if you verified that the contract exists at the canonical address, deployment succeeded.

>"message" must be a nonempty string. 

This is very strange, there's no `message` variable anywhere on `RelayHub`, and `getRelay` is a very simple function. Are you sure you're setting up Remix correctly to call it?

**Comment by crossoveranx** [comment]
@nventuro The contract is deployed here at the typical address: https://blockexplorer.bloxberg.org/address/0xd216153c06e857cd7f72665e0af1d7d82172f494/transactions, so I can confirm it exists.

I use remixd in order to connect my local contracts to remix. As a test, I connect to another network via Metamask, for instance Ropsten or Rinkeby, and try calling the IRelayHub functions. I can confirm that these work as intended. When I switch Metamask to my private network with the deployed contract, it returns the above error "message" must be a nonempty string.

Having trouble figuring out exactly why the RelayHub deployed to our network is returning these errors. Is there an initialize function I have to call beforehand or any other dependency? For reference, I deployed the contracts from the tabookey repository

**Comment by nventuro** [comment]
There is no initialization that you need to run, and the fact that the address where it is deployed is the same one verifies that the bytecode is exactly the same one.

From your description, it looks like there might be an issue with Metamask itself in your private network, since the contracts you're interacting with are the same. Have you tried using Metamask with other contracts there?

**Comment by crossoveranx** [comment]
Yes, metamask works fine with other contracts. I don't believe it's a problem with metamask as I have also tried registering the relay via code using this library and I receive a reverted transaction. 

One thing to note is that I'm using parity instead of geth. Not sure if this is entirely relevant, but if you have any further troubleshooting suggestions I would be happy to try.

**Comment by nventuro** [comment]
Can you share more information on the `"message" must be a nonempty string` error? Who is emitting it? Is there any additional contextual information?

**Comment by crossoveranx** [comment]
Okay, now I switched from Metamask to another wallet extension. Now I am getting the error 'Internal JSON-RPC error'. Just to be clear, I should be calling the functions from the IRelayHub contract as opposed to RelayHub?

```
status 	0x0 Transaction mined but execution failed

 transaction hash 	0x19e88ac02752648b54b120c0a0eed69e4ff415f1a38fc93674891a8312b69d32

 from 	0xaa84378fa41da83a9b6523ba46e45a664fbebfc8

 to 	0xd216153c06e857cd7f72665e0af1d7d82172f494 

0xd216153c06e857cd7f72665e0af1d7d82172f494

 gas 	6000000 gas 

 transaction cost 	6000000 gas 

 hash 	0x19e88ac02752648b54b120c0a0eed69e4ff415f1a38fc93674891a8312b69d32

 input 	0xadc9772e000000000000000000000000f8c95e2edf9a4443117f5f514043f284feae5acb0000000000000000000000000000000000000000000000000000000000093a80

 decoded input 	 - 

 decoded output 	 - 

 value 	5000000000000000000 wei 
```

Here is the associated transaction

**Comment by nventuro** [comment]
Hm, you're calling the method correctly (`0xadc9772e` is the selector for `stake`), but it is very strange that the transaction cost is the same as the gas limit. There are no `throw` statements in the code, so the contract shouldn't fail in that way.

How similar is your private VM to the Ethereum VM? Is it possible its running based on an older version, and we're hitting invalid opcodes?

**Comment by crossoveranx** [comment]
Yes, that's certainly possible. We are currently running Byzantium and perhaps we need to upgrade to Istanbul at this point to utilize new features. Is there a way I can check whether the transaction is failing because of the invalid op codes? Normally, I get an error message stating as such.

**Comment by nventuro** [comment]
To be frank I have no idea where that bizarre 'message must not be empty' error comes from. However, I'd say that the transaction failing and consuming all allocated gas is a pretty strong sign of invalid opcode behaviour.

**Comment by crossoveranx** [comment]
Okay - thanks for your help. Since I deployed the initial contracts with the latest EVM, the methods would consistently fail. What ended up working is compiling and redeploying with Byzantium and I could stake the contract - hopefully this is helpful for others that run into a similar issue while using a private chain

**Comment by nventuro** [comment]
It's great that you got it sorted out! Keep in mind that since you're recompiling the code with a different target EVM, the resulting bytecode will be different from the canonical one, which will in turn result in the RelayHub contract not being located at the same address. 

Our tools are designed to receive an arbitrary RelayHub address though, so you should still be able to use them by making sure you don't rely on the default RelayHub.
