### ISSUE TITLE
Helper to shutdown / stop /kill the relay server

### ISSUE THREAD

**Issue by rrodriguezreche** [OpenZeppelin/openzeppelin-gsn-helpers#29]
I am trying to use GSN in a test environment with truffle + ganache, and gulp for running tests automatically (my guess is nodemon would also be affected). It seems like the relayer is reattaching to the parent node process when truffle finishes the test, so the relayer is kept alive after the test run ends, spamming messages and requiring to kill the gulp / nodemon process.

![image](https://user-images.githubusercontent.com/46090742/75701099-6d3f7c80-5cb3-11ea-8fb9-f9cd50a7699f.png)

A straight forward way to avoid this would be to add an "after" hook in the test and calling a helper to shutdown the relayer server, but I have not seen this neither in the docs nor in the exported helpers for the package.

A workaround would be to keep ganache alive and instantiate the relayer "externally".

I will try to do it myself but don't count on it :joy:

EDIT. Oh well, diving into the source it seems like `runRelayer` actually returns the node subprocess. I will try to kill it and if sucessful, close the issue.

EDIT2. Done, I am leaving a code snippet

In a `before` hook:
```
relayHubProcess = await runRelayer({ web3, quiet: true, detach: true });
```

In the `after` hook:
```
after('kill relayhub', async () => {
    if (
      relayHubProcess &&
      !relayHubProcess.killed &&
      typeof relayHubProcess.kill === 'function'
    ) {
      await relayHubProcess.kill();
      if (!relayHubProcess.killed) {
        console.warn('Relayer was not killed');
      }
    }
  });
```

Closing the issue!

**Comment by nventuro** [comment]
I'm glad to hear you got this sorted out @rrodriguezreche! For testing enviroments, you can also [use the GSNDevProvider](https://docs.openzeppelin.com/gsn-provider/0.1/testing-gsn-applications#using_the_development_provider), which may simplify things further.
